import unittest
import pytest
import os
import sys
import threading
from pathlib import Path
from config.config import config
from common.log import log
from push.push_manager import push_manager


class Runner:
    def __init__(self):
        self.base_dir = Path(__file__).parent.parent
        self.test_cases_dir = self.base_dir / "test_cases"
        self.reports_dir = self.base_dir / "reports"
        if not os.path.exists(self.reports_dir):
            os.makedirs(self.reports_dir)
        self.thread_count = config.get('thread_count', 1)

    def run_with_unittest(self):
        log.info("Running tests with unittest")
        test_loader = unittest.TestLoader()
        test_suite = test_loader.discover(str(self.test_cases_dir))

        # 使用 XTestRunner 生成 HTML 报告
        html_dir = self.reports_dir / "html"
        if not os.path.exists(html_dir):
            os.makedirs(html_dir)

        # 读取 XTestRunner 配置
        xtestrunner_config = config.get('reports.xtestrunner', {})
        title = xtestrunner_config.get('title', "API Automated Test Report")
        description = xtestrunner_config.get('description', "Generated by XTestRunner")
        language = xtestrunner_config.get('language', "zh-CN")
        retry = xtestrunner_config.get('retry', 0)
        tester = xtestrunner_config.get('tester', "Test")

        from XTestRunner import HTMLTestRunner
        runner = HTMLTestRunner(
            output=str(html_dir),
            title=title,
            description=description,
            language=language,
            retry=retry,
            tester=tester
        )

        result = runner.run(test_suite)

        self._send_notification(result)
        return result

    def run_with_pytest(self):
        log.info("Running tests with pytest")

        pytest_args = [
            str(self.test_cases_dir),
            "-v"
        ]

        if config.get('reports.allure', False):
            allure_dir = self.reports_dir / "allure-results"
            if not os.path.exists(allure_dir):
                os.makedirs(allure_dir)
            pytest_args.extend(["--alluredir", str(allure_dir)])

        if config.get('reports.html', False):
            html_dir = self.reports_dir / "html"
            if not os.path.exists(html_dir):
                os.makedirs(html_dir)

            # 读取 pytest-xhtml 配置
            pytest_xhtml_config = config.get('reports.pytest_xhtml', {})
            self_contained = pytest_xhtml_config.get('self_contained', True)
            css_files = pytest_xhtml_config.get('css', [])

            pytest_args.extend(["--html", str(html_dir / "report.html")])
            for css in css_files:
                pytest_args.extend(["--css", css])

        if self.thread_count > 1:
            pytest_args.extend([f"-n", str(self.thread_count)])

        result = pytest.main(pytest_args)

        if config.get('reports.allure', False):
            self._generate_allure_report()

        self._send_notification(result)
        return result

    def _generate_allure_report(self):
        log.info("Generating Allure report")
        allure_results = self.reports_dir / "allure-results"
        allure_report = self.reports_dir / "allure-report"

        import subprocess
        import shutil
        import os

        # 检查 allure 命令是否存在
        allure_cmd = shutil.which("allure")
        if allure_cmd:
            log.info(f"Found Allure command at: {allure_cmd}")
            try:
                # 尝试运行 allure 命令
                result = subprocess.run(
                    [allure_cmd, "generate", str(allure_results), "-o", str(allure_report), "--clean"],
                    check=True, capture_output=True, text=True)
                log.info(f"Allure report generated at: {allure_report}")
                log.debug(f"Allure output: {result.stdout}")
            except subprocess.CalledProcessError as e:
                log.error(f"Failed to generate Allure report: {e.stderr}")
            except Exception as e:
                log.error(f"Failed to generate Allure report: {str(e)}")
        else:
            # 尝试从常见路径查找 allure
            common_paths = [
                "C:\\Program Files\\Allure\\bin\\allure.bat",  # Windows
                "C:\\Program Files (x86)\\Allure\\bin\\allure.bat",  # Windows 32-bit
                "/usr/local/bin/allure",  # Linux/Mac
                "/opt/allure/bin/allure",  # Linux
            ]

            found = False
            for path in common_paths:
                if os.path.exists(path):
                    allure_cmd = path
                    found = True
                    break

            if found:
                log.info(f"Found Allure command at: {allure_cmd}")
                try:
                    result = subprocess.run(
                        [allure_cmd, "generate", str(allure_results), "-o", str(allure_report), "--clean"],
                        check=True, capture_output=True, text=True)
                    log.info(f"Allure report generated at: {allure_report}")
                    log.debug(f"Allure output: {result.stdout}")
                except subprocess.CalledProcessError as e:
                    log.error(f"Failed to generate Allure report: {e.stderr}")
                except Exception as e:
                    log.error(f"Failed to generate Allure report: {str(e)}")
            else:
                log.warning("Allure command not found. Please install Allure to generate the report.")
                log.info(f"Allure results saved at: {allure_results}")
                log.info("To generate the report, run: allure generate <allure-results> -o <allure-report> --clean")

    def _send_notification(self, result):
        if isinstance(result, unittest.TestResult):
            total = result.testsRun
            passed = total - len(result.failures) - len(result.errors)
            failed = len(result.failures)
            errors = len(result.errors)
        else:
            total = "N/A"
            passed = "N/A"
            failed = "N/A"
            errors = "N/A"

        subject = "API Automated Test Report"
        content = f"""
        <h2>Test Report</h2>
        <p>Total Tests: {total}</p>
        <p>Passed: {passed}</p>
        <p>Failed: {failed}</p>
        <p>Errors: {errors}</p>
        <p>Report directory: {self.reports_dir}</p>
        """

        push_manager.send_notification(subject, content)


runner = Runner()
